In [2]:
import pandas as pd
gas_prices=pd.read_excel("data/raw/avgprice_annual.xlsx")
gas_prices.head()

,"Average Price (Cents/kilowatthour) by State by Provider, 1990-2020",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Year,State,Industry Sector Category,Residential,Commercial,Industrial,Transportation,Other,Total
1,2020,AK,Total Electric Industry,22.57,19.58,15.88,0,NaN,19.82
2,2020,AL,Total Electric Industry,12.58,11.55,5.87,0,NaN,9.84
3,2020,AR,Total Electric Industry,10.41,8.61,5.89,13.32,NaN,8.32
4,2020,AZ,Total Electric Industry,12.27,10.11,6.07,9.38,NaN,10.44

In [3]:
gas_prices=pd.read_excel("data/raw/avgprice_annual.xlsx", skiprows=1)
gas_prices.head()

,Year,State,Industry Sector Category,Residential,Commercial,Industrial,Transportation,Other,Total
0,2020,AK,Total Electric Industry,22.57,19.58,15.88,0.00,NaN,19.82
1,2020,AL,Total Electric Industry,12.58,11.55,5.87,0.00,NaN,9.84
2,2020,AR,Total Electric Industry,10.41,8.61,5.89,13.32,NaN,8.32
3,2020,AZ,Total Electric Industry,12.27,10.11,6.07,9.38,NaN,10.44
4,2020,CA,Total Electric Industry,20.45,17.53,14.27,10.07,NaN,18.00

In [5]:
gas_prices.shape

(4605, 9)

In [6]:
gas_prices.info()

<class 'pandas.DataFrame'>
RangeIndex: 4605 entries, 0 to 4604
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      4605 non-null   int64
 1   State                     4605 non-null   str
 2   Industry Sector Category  4605 non-null   str
 3   Residential               4605 non-null   float64
 4   Commercial                4605 non-null   float64
 5   Industrial                4605 non-null   float64
 6   Transportation            2998 non-null   float64
 7   Other                     1607 non-null   float64
 8   Total                     4605 non-null   float64
dtypes: float64(6), int64(1), str(2)
memory usage: 323.9 KB

In [8]:
is_us=gas_prices["State"]=="US"
is_2020=gas_prices["Year"]==2020
is_total=gas_prices["Industry Sector Category"]=="Total Electric Industry"
us_2020=gas_prices[is_us & is_2020 & is_total]
us_2020

,Year,State,Industry Sector Category,Residential,Commercial,Industrial,Transportation,Other,Total
51,2020,US,Total Electric Industry,13.15,10.59,6.67,9.9,NaN,10.59

In [9]:
us_over_time=gas_prices[is_us & is_total]
us_over_time

,Year,State,Industry Sector Category,Residential,Commercial,Industrial,Transportation,Other,Total
51,2020,US,Total Electric Industry,13.15,10.59,6.67,9.90,NaN,10.59
218,2019,US,Total Electric Industry,13.01,10.68,6.81,9.66,NaN,10.54
385,2018,US,Total Electric Industry,12.87,10.67,6.92,9.70,NaN,10.53
552,2017,US,Total Electric Industry,12.89,10.66,6.88,9.68,NaN,10.48
719,2016,US,Total Electric Industry,12.55,10.43,6.76,9.63,NaN,10.27
886,2015,US,Total Electric Industry,12.65,10.64,6.91,10.09,NaN,10.41
1053,2014,US,Total Electric Industry,12.52,10.74,7.10,10.45,NaN,10.44
1220,2013,US,Total Electric Industry,12.13,10.26,6.89,10.55,NaN,10.07
1384,2012,US,Total Electric Industry,11.88,10.09,6.67,10.21,NaN,9.84
1548,2011,US,Total Electric Industry,11.72,10.24,6.82,10.46,NaN,9.90
1712,2010,US,Total Electric Industry,11.54,10.19,6.77,10.56,NaN,9.83
1879,2009,US,Total Electric Industry,11.51,10.16,6.83,10.66,NaN,9.82
2049,2008,US,Total Electric Industry,11.26,10.26,6.96,10.71,NaN,9.74
2219,2007,US,Total Electric Industry,10.65,9.65,6.39,9.70,NaN,9.13
2386,2006,US,Total Electric Industry,10.40,9.46,6.16,9.54,NaN,8.90
2553,2005,US,Total Electric Industry,9.45,8.67,5.73,8.57,NaN,8.14
2720,2004,US,Total Electric Industry,8.95,8.17,5.25,7.18,NaN,7.61
2888,2003,US,Total Electric Industry,8.72,8.03,5.11,7.54,NaN,7.44
3049,2002,US,Total Electric Industry,8.44,7.89,4.88,NaN,6.75,7.20
3210,2001,US,Total Electric Industry,8.58,7.92,5.05,NaN,7.20,7.29
3374,2000,US,Total Electric Industry,8.24,7.43,4.64,NaN,6.56,6.81
3530,1999,US,Total Electric Industry,8.16,7.26,4.43,NaN,6.35,6.64
3670,1998,US,Total Electric Industry,8.26,7.41,4.48,NaN,6.63,6.74
3798,1997,US,Total Electric Industry,8.43,7.59,4.53,NaN,6.91,6.85
3926,1996,US,Total Electric Industry,8.36,7.64,4.60,NaN,6.91,6.86
4032,1995,US,Total Electric Industry,8.40,7.69,4.66,NaN,6.88,6.89
4136,1994,US,Total Electric Industry,8.38,7.73,4.77,NaN,6.84,6.91
4240,1993,US,Total Electric Industry,8.32,7.74,4.85,NaN,6.88,6.93
4344,1992,US,Total Electric Industry,8.21,7.66,4.83,NaN,6.74,6.82
4448,1991,US,Total Electric Industry,8.04,7.53,4.83,NaN,6.51,6.75
4552,1990,US,Total Electric Industry,7.83,7.34,4.74,NaN,6.40,6.57

In [12]:
us_trend=us_over_time[["Year","Total"]] #double brackets for different columns
us_trend=us_trend.sort_values("Year")
us_trend = us_trend.reset_index(drop=True)
us_trend

    Year  Total
0   1990   6.57
1   1991   6.75
2   1992   6.82
3   1993   6.93
4   1994   6.91
5   1995   6.89
6   1996   6.86
7   1997   6.85
8   1998   6.74
9   1999   6.64
10  2000   6.81
11  2001   7.29
12  2002   7.20
13  2003   7.44
14  2004   7.61
15  2005   8.14
16  2006   8.90
17  2007   9.13
18  2008   9.74
19  2009   9.82
20  2010   9.83
21  2011   9.90
22  2012   9.84
23  2013  10.07
24  2014  10.44
25  2015  10.41
26  2016  10.27
27  2017  10.48
28  2018  10.53
29  2019  10.54
30  2020  10.59

In [13]:
us_trend.describe()

              Year      Total
count    31.000000  31.000000
mean   2005.000000   8.481935
std       9.092121   1.593230
min    1990.000000   6.570000
25%    1997.500000   6.875000
50%    2005.000000   8.140000
75%    2012.500000   9.985000
max    2020.000000  10.590000